title: Home
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gralavia.github.io

aux_links:
  Github Profile: https://github.com/gralavia
